application: vristbryllup
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon

- url: /robot.txt
  static_files: static/robot.txt
  upload: static/robot.txt

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin


- url: .*
  script: main.py
